# Generated by Django 5.2.6 on 2025-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('location', models.JSONField(blank=True, null=True)),
                ('area', models.JSONField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('propertyType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('amenities', models.JSONField()),
                ('agent', models.JSONField()),
                ('dateListed', models.DateTimeField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
